# Generated by Django 6.1.1 on 2026-09-18 12:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('program', models.CharField(choices=[('BTECH', 'B.Tech'), ('MTECH', 'M.Tech'), ('PHD', 'PhD')], max_length=10)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('MST', 'Mathematics & Scientific Computing')], max_length=10)),
                ('year', models.PositiveSmallIntegerField(help_text='Year of study this course belongs to')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExamSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session_number', models.PositiveSmallIntegerField(default=1, help_text='Which session of the day this is (a day may have up to 4 sessions)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['date', 'session_number'],
            },
        ),
        migrations.CreateModel(
            name='ExamTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('MID', 'Mid-Term'), ('END', 'End-Term')], max_length=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('students_per_invigilator', models.PositiveSmallIntegerField(default=30)),
                ('reserves_per_hall', models.PositiveSmallIntegerField(default=1)),
                ('min_gap_minutes', models.PositiveIntegerField(default=0, help_text='Minimum gap required between two exams for the same student')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('kind', models.CharField(choices=[('FACULTY', 'Faculty'), ('SCHOLAR', 'Research Scholar')], max_length=10)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('MST', 'Mathematics & Scientific Computing')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Faculty',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('is_accessible', models.BooleanField(default=False, help_text='Ground floor / accessible for PwD students')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolment_number', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('program', models.CharField(choices=[('BTECH', 'B.Tech'), ('MTECH', 'M.Tech'), ('PHD', 'PhD')], max_length=10)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('MST', 'Mathematics & Scientific Computing')], max_length=10)),
                ('year', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['enrolment_number'],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField(default=180)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='portal.course')),
                ('exam_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='portal.examslot')),
                ('exam_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='portal.examterm')),
            ],
            options={
                'ordering': ['exam_slot__date', 'exam_slot__start_time'],
                'unique_together': {('exam_term', 'course')},
            },
        ),
        migrations.AddField(
            model_name='examslot',
            name='exam_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='portal.examterm'),
        ),
        migrations.CreateModel(
            name='BenchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. "3-seater bench"', max_length=50)),
                ('bench_count', models.PositiveSmallIntegerField()),
                ('seats_per_bench', models.PositiveSmallIntegerField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bench_groups', to='portal.hall')),
            ],
            options={
                'ordering': ['-seats_per_bench', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HallAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_density', models.CharField(choices=[('FULL', 'Full bench capacity'), ('SINGLE', 'One seat per bench (spread out)')], default='SINGLE', max_length=10)),
                ('seating_mode', models.CharField(choices=[('ROLL_ORDER', 'Roll number order'), ('SHUFFLED', 'Shuffled across courses')], default='ROLL_ORDER', max_length=10)),
                ('exam_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_allocations', to='portal.examschedule')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_allocations', to='portal.hall')),
            ],
            options={
                'unique_together': {('exam_schedule', 'hall')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='portal.examterm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EXTRA_TIME', 'Extra time'), ('SCRIBE', 'Scribe'), ('GROUND_FLOOR', 'Ground floor hall'), ('SEPARATE_ROOM', 'Separate room')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='portal.student')),
            ],
            options={
                'ordering': ['student__enrolment_number'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='examslot',
            unique_together={('exam_term', 'date', 'session_number')},
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('INVIGILATOR', 'Invigilator'), ('RESERVE', 'Reserve')], max_length=15)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ACKNOWLEDGED', 'Acknowledged'), ('DROPPED', 'Dropped'), ('REASSIGNED', 'Reassigned')], default='ASSIGNED', max_length=15)),
                ('exam_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='portal.examschedule')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='portal.faculty')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='portal.hall')),
            ],
            options={
                'unique_together': {('exam_schedule', 'hall', 'faculty')},
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('exam_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='portal.examterm')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('exam_term', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_number', models.PositiveSmallIntegerField()),
                ('seat_position', models.PositiveSmallIntegerField()),
                ('bench_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='portal.benchgroup')),
                ('hall_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='portal.hallallocation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='portal.student')),
            ],
            options={
                'ordering': ['bench_group', 'bench_number', 'seat_position'],
                'unique_together': {('hall_allocation', 'bench_group', 'bench_number', 'seat_position')},
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='portal.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='portal.student')),
            ],
            options={
                'unique_together': {('course', 'student')},
            },
        ),
    ]
